Rebuild for PyPy3.8 and PyPy3.9 (#8)
* Rebuild for PyPy3.8 and PyPy3.9

* MNT: Re-rendered with conda-build 3.22.0, conda-smithy 3.21.1, and conda-forge-pinning 2022.08.25.01.17.35

* MutableMapping import doesn't work for Py3.10

Address error "AttributeError: module 'collections' has no attribute 'MutableMapping'"

* fix python pin

* Revert "fix python pin"

This reverts commit d4df253e1797605d975a12c06efd05dcf3be0311.

* Revert "MutableMapping import doesn't work for Py3.10"

This reverts commit 171d87c989865fbf31af5b6aa94011512f0d4b19.

* Pin python pin with noarch

* MNT: Re-rendered with conda-build 3.22.0, conda-smithy 3.21.1, and conda-forge-pinning 2022.08.25.07.46.09

Co-authored-by: Jonathan Manning <jonathan.manning@healx.io>
Co-authored-by: conda-forge-webservices[bot] <91080706+conda-forge-webservices[bot]@users.noreply.github.com>